export const players = [
  { id: 1, name: "Bertil Gustafsson", points: 0 },
  { id: 2, name: "Berra Gustafsson", points: 0 },
  { id: 3, name: "Eva Andersson", points: 0 },
  { id: 4, name: "Eva kAndersson", points: 0 },
  { id: 5, name: "Petter Gustafsson", points: 0 },
  { id: 6, name: "Petter Eriksson", points: 0 },
  { id: 7, name: "Anna Gustafsson", points: 0 },
  { id: 8, name: "Anna kGustafsson", points: 0 },
  { id: 9, name: "Per Gustafsson", points: 0 },
  { id: 10, name: "Peter Wiklund", points: 0 },
  { id: 11, name: "Eva Egmalm", points: 0 },
  { id: 12, name: "Anders Liljedahl", points: 0 },
  { id: 13, name: "Ida Gustafsson", points: 0 },
  { id: 14, name: "Tommy ??", points: 0 },
  { id: 15, name: "Viktor Gustafsson", points: 0 },
  { id: 16, name: "Mark Holmberg", points: 0 },
  { id: 17, name: "Nils Gustafsson", points: 0 },
  { id: 18, name: "Johan Warg", points: 0 },
  { id: 19, name: "Sandra Rannerud", points: 0 },
  { id: 20, name: "Johan Söderberg", points: 0 },
  { id: 21, name: "Jimmy Riddermark", points: 0 },
  { id: 22, name: "Jimmy kompis", points: 0 },
  { id: 23, name: "Andrew Cameron-Webb", points: 0 },
  { id: 24, name: "Andrew kompis", points: 0 },
];

export const matches = [
  {
    id: 1,
    date: "11-jun",
    home: "Mexico",
    away: "South Africa",
    group: "A",
    result: null,
    tips: {
      "Bertil Gustafsson": { home: 0, away: 2, sign: "1" },
      "Berra Gustafsson": { home: 1, away: 1, sign: "2" },
      "Eva Andersson": { home: 2, away: 1, sign: "1" },
      "Eva kAndersson": { home: 0, away: 3, sign: "1" },
      "Petter Gustafsson": { home: 1, away: 2, sign: "2" },
      "Petter Eriksson": { home: 0, away: 1, sign: "X" },
      "Anna Gustafsson": { home: 2, away: 2, sign: "1" },
      "Anna kGustafsson": { home: 1, away: 2, sign: "2" },
      "Per Gustafsson": { home: 0, away: 2, sign: "X" },
      "Peter Wiklund": { home: 1, away: 0, sign: "2" },
      "Eva Egmalm": { home: 2, away: 3, sign: "1" },
      "Anders Liljedahl": { home: 0, away: 2, sign: "X" },
      "Ida Gustafsson": { home: 1, away: 1, sign: "2" },
      "Tommy ??": { home: 0, away: 3, sign: "1" },
      "Viktor Gustafsson": { home: 1, away: 2, sign: "X" },
      "Mark Holmberg": { home: 2, away: 1, sign: "2" },
      "Nils Gustafsson": { home: 0, away: 2, sign: "1" },
      "Johan Warg": { home: 1, away: 3, sign: "X" },
      "Sandra Rannerud": { home: 2, away: 2, sign: "2" },
      "Johan Söderberg": { home: 1, away: 2, sign: "1" },
      "Jimmy Riddermark": { home: 0, away: 1, sign: "X" },
      "Jimmy kompis": { home: 1, away: 2, sign: "2" },
      "Andrew Cameron-Webb": { home: 2, away: 0, sign: "X" },
      "Andrew kompis": { home: 0, away: 2, sign: "1" },
    },
  },
  {
    id: 2,
    date: "12-jun",
    home: "South Korea",
    away: "Czechia",
    group: "A",
    result: null,
    tips: {
      "Bertil Gustafsson": { home: 0, away: 2, sign: "X" },
      "Berra Gustafsson": { home: 1, away: 1, sign: "2" },
      "Eva Andersson": { home: 2, away: 1, sign: "X" },
      "Eva kAndersson": { home: 0, away: 3, sign: "1" },
      "Petter Gustafsson": { home: 1, away: 2, sign: "X" },
      "Petter Eriksson": { home: 0, away: 1, sign: "X" },
      "Anna Gustafsson": { home: 2, away: 2, sign: "X" },
      "Anna kGustafsson": { home: 1, away: 2, sign: "2" },
      "Per Gustafsson": { home: 0, away: 2, sign: "X" },
      "Peter Wiklund": { home: 1, away: 0, sign: "2" },
      "Eva Egmalm": { home: 2, away: 3, sign: "1" },
      "Anders Liljedahl": { home: 0, away: 2, sign: "X" },
      "Ida Gustafsson": { home: 1, away: 1, sign: "2" },
      "Tommy ??": { home: 0, away: 3, sign: "1" },
      "Viktor Gustafsson": { home: 1, away: 2, sign: "X" },
      "Mark Holmberg": { home: 2, away: 1, sign: "2" },
      "Nils Gustafsson": { home: 0, away: 2, sign: "1" },
      "Johan Warg": { home: 1, away: 3, sign: "X" },
      "Sandra Rannerud": { home: 2, away: 2, sign: "2" },
      "Johan Söderberg": { home: 1, away: 2, sign: "1" },
      "Jimmy Riddermark": { home: 0, away: 1, sign: "X" },
      "Jimmy kompis": { home: 1, away: 2, sign: "2" },
      "Andrew Cameron-Webb": { home: 2, away: 0, sign: "X" },
      "Andrew kompis": { home: 0, away: 2, sign: "1" },
    },
  },
];

export const predictions = {
  "Bertil Gustafsson": {
    roundOf32: [
      "Brazil",
      "France",
      "Argentina",
      "England",
      "Spain",
      "Germany",
      "Portugal",
      "Netherlands",
      "Belgium",
      "Uruguay",
      "Colombia",
      "Mexico",
      "United States",
      "Japan",
      "Morocco",
      "Senegal",
      "Croatia",
      "Denmark",
      "Switzerland",
      "Poland",
      "South Korea",
      "Australia",
      "Ecuador",
      "Ghana",
      "Cameroon",
      "Serbia",
      "Canada",
      "Wales",
      "Iran",
      "Qatar",
      "Saudi Arabia",
      "Tunisia",
    ],
    roundOf16: [
      "Brazil",
      "France",
      "Argentina",
      "England",
      "Spain",
      "Germany",
      "Portugal",
      "Netherlands",
    ],
    quarterFinals: ["Brazil", "France", "Argentina", "England"],
    semiFinals: ["Brazil", "France"],
    finals: ["Brazil", "France"],
    bronzeWinner: "Argentina",
    worldChampion: "Brazil",
    topScorer: "Mbappe",
    mostGoalsTeam: "France",
    mostConcededTeam: "Saudi Arabia",
    swedenGoals: 4,
    fastestGoal: "Brazil",
  },
  "Anna Gustafsson": {
    roundOf32: [
      "Brazil",
      "France",
      "Argentina",
      "England",
      "Spain",
      "Germany",
      "Portugal",
      "Netherlands",
      "Belgium",
      "Uruguay",
      "Colombia",
      "Mexico",
      "United States",
      "Japan",
      "Morocco",
      "Senegal",
      "Croatia",
      "Denmark",
      "Switzerland",
      "Poland",
      "South Korea",
      "Australia",
      "Ecuador",
      "Ghana",
      "Cameroon",
      "Serbia",
      "Canada",
      "Wales",
      "Iran",
      "Qatar",
      "Saudi Arabia",
      "Tunisia",
    ],
    roundOf16: [
      "Argentina",
      "England",
      "Spain",
      "Germany",
      "Portugal",
      "Netherlands",
      "Belgium",
      "Uruguay",
    ],
    quarterFinals: ["Argentina", "England", "Spain", "Germany"],
    semiFinals: ["Argentina", "England"],
    finals: ["Argentina", "England"],
    bronzeWinner: "Spain",
    worldChampion: "Argentina",
    topScorer: "Messi",
    mostGoalsTeam: "Argentina",
    mostConcededTeam: "Iran",
    swedenGoals: 3,
    fastestGoal: "Argentina",
  },
};
